---
- name: Deploy Containerized Minecraft Server
  hosts: all
  become: yes
  vars:
    ecr_registry_url: "339712850345.dkr.ecr.us-east-1.amazonaws.com/cs312-igloriaj-ops3"
    s3_bucket: "cs312-igloriaj-ops3-backups"
    image_tag: "v1.0.2"

  tasks:
    - name: Install curl and aws cli
      apt:
        name:
          - curl
          - awscli
        state: present
        update_cache: yes

    - name: Create local-path destination folder
      file:
        path: /var/lib/rancher/k3s/storage/pvc-minecraft_data
        state: directory
        owner: root
        group: root
        mode: '0777'

    - name: Restore World from S3 if exists
      shell: "aws s3 cp s3://{{ s3_bucket }}/world_backup.tar.gz /tmp/world_backup.tar.gz || echo 'No backup found'"
      register: s3_download
      failed_when: "'Completed' not in s3_download.stderr and s3_download.rc != 0"
      ignore_errors: yes      

    - name: Check if backup was downloaded
      stat:
        path: /tmp/world_backup.tar.gz
      register: backup_file

    - name: Extract backup to /data
      unarchive:
        src: /tmp/world_backup.tar.gz
        dest: /var/lib/rancher/k3s/storage/pvc-minecraft_data
        remote_src: yes
      when: backup_file.stat.exists

    - name: Download the AWS ECR Credential Provider binary
      get_url:
        url: https://github.com/dntosas/ecr-credential-provider/releases/download/v1.2.0/ecr-credential-provider-linux-amd64
        dest: /usr/local/bin/ecr-credential-provider
        mode: '0755'
        owner: root
        group: root

    - name: Create Kubernetes configuration directory
      file:
        path: /etc/kubernetes
        state: directory
        owner: root
        group: root
        mode: '0755' 

    - name: Create CredentialProviderConfig configuration file
      copy:
        dest: /etc/kubernetes/ecr-credential-provider.json
        owner: root
        group: root
        mode: '0644'
        content: |
          apiVersion: kubelet.config.k8s.io/v1
          kind: CredentialProviderConfig
          providers:
            - name: ecr-credential-provider
              matchImages:
                - "*.dkr.ecr.*.amazonaws.com"
                - "*.dkr.ecr.*.amazonaws.com.cn"
                - "*.dkr.ecr-fips.*.amazonaws.com"
                - "*.dkr.ecr.us-iso-east-1.c2s.ic.gov"
                - "*.dkr.ecr.us-isob-east-1.sc2s.sgov.gov"
              defaultCacheDuration: "12h"
              apiVersion: credentialprovider.kubelet.k8s.io/v1

    - name: Install k3s linked to the AWS credential provider
      shell: |
        curl -sfL https://get.k3s.io | sh -s - \
          --kubelet-arg="image-credential-provider-config=/etc/kubernetes/ecr-credential-provider.json" \
          --kubelet-arg="image-credential-provider-bin-dir=/usr/local/bin"
      args:
        creates: /usr/local/bin/k3s

    - name: Ensure k3s is started and enabled
      service:
        name: k3s
        state: started
        enabled: yes

    - name: Wait for cluster to initialize and generation of config file
      wait_for:
        path: /etc/rancher/k3s/k3s.yaml
        state: present
    
    - name: Create .kube directory for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0750'

    - name: Copy k3s.yaml to user's directory
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: add KUBECONFIG to .bashrc
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: 'export KUBECONFIG=~/.kube/config'
        state: present
        create: yes

    - name: Install Helm
      shell: |
        curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      become: true
    
    - name: Add Prometheus Helm repository
      shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
      become: false
      changed_when: true

    - name: Deploy kube-prometheus-stack
      shell: |
        helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
          --namespace monitoring --create-namespace \
          --set grafana.service.type=NodePort \
          --set grafana.service.nodePort=31000 \
          --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false \
          --set prometheus.prometheusSpec.ruleSelectorNilUsesHelmValues=false \
          --set grafana.sidecar.image.tag=1.28.0
      become: false
      changed_when: true

    - name: Copy Minecraft Kubernetes Manifest to server
      copy:
        src: minecraft.yaml
        dest: /home/ubuntu/minecraft.yaml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Apply minecraft workload config in k3s
      shell: "k3s kubectl apply -f /home/ubuntu/minecraft.yaml"


